name: Tag-zip release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-prerelease

    paths-ignore:
      - '**/README.md'

jobs:
  tag-to-release:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: communitiesuk/funding-design-service-workflows/.github/workflows/tag-to-release.yml@main
